proxy:
  type: "socks" # socks/ssh/chisel
interface:
  device: "tun0"
  exclude:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  metric: 512
  # custom_routes: # ip ro add
  #   - "192.168.200.53 via 192.168.200.1 dev virbr0"
socks:
  proto: "socks5" # socks5/ss/relay
  username: "username"
  password: "password"
  host: "127.0.0.1"
  port: 9050
  extra: ""
ssh:
  username: "user"
  host: "192.168.1.1"
  port: 22
  extra: ""
chisel:
  server: "https://chisel.com"
  username: "username"
  password: "password"
  proxy: "socks5h://proxy_username:proxy_password@1.3.3.7:1080" # only support http/socks5h/socks
# warning: udp not route to proxy, t2s route only tcp
dns:
  listen: "127.1.1.53"
  render: true
  resolvers:
    # - "127.1.2.53:53/tcp"
    - "1.1.1.1:53/tcp"
    # - "10.10.10.1:53/udp"
  records:
    test.lan: "10.10.10.10"
