version: "3"

vars:
  gobin: go
  ldflags: "-extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "tun2socksme"
  app_bin: "{{.bin}}/{{.app}}"
  remote_user: astra
  remote_host: 192.168.200.33
  remote_dir: "~/"

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  setup:
    desc: Set up the environment
    silent: true
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: Build application
    deps: [setup]
    silent: true
    cmds:
      - >
        {{.gobin}} build
        -tags netgo
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.app_bin}} cmd/{{.app}}/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  test:
    desc: Run on remote with scp
    deps: [build]
    silent: true
    cmds:
      - sudo {{.bin}}/{{.app}} -config config.override.yaml
      # - scp {{.app_bin}} {{.remote_user}}@{{.remote_host}}:{{.remote_dir}}
      # - scp config.override.yaml {{.remote_user}}@{{.remote_host}}:{{.remote_dir}}
      # Uncomment the following line to run the app remotely
      # - ssh {{.remote_user}}@{{.remote_host}} 'sudo {{.remote_dir}}/{{.app}} -config config.override.yaml'

  dns:
    desc: Build and deploy DNS tool
    deps: [setup]
    cmds:
      - >
        {{.gobin}} build 
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.bin}}/dns dns.go
      - strip {{.bin}}/dns
      - objcopy --strip-unneeded {{.bin}}/dns
      - scp {{.bin}}/dns {{.remote_user}}@{{.remote_host}}:{{.remote_dir}}
