version: "3"

vars:
  gobin: go
  ldflags: "-extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "tun2socksme"
  app_bin: "{{.bin}}/{{.app}}"

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  default:
    desc: Show help
    cmds:
      - "{{.bin}}/task --list"

  setup:
    desc: Set up the environment
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: Build application
    deps: [setup]
    cmds:
      - |
        {{.gobin}} build -ldflags="{{.ldflags}}" -trimpath -gcflags="{{.gcflags}}" -asmflags="{{.asmflags}}" \
          -o {{.app_bin}} cmd/{{.app}}/main.go
        strip {{.app_bin}}
        objcopy --strip-unneeded {{.app_bin}}

  test:
    desc: Run on remote with scp
    deps: [build]
    cmds:
      - |
        ssh-copy-id astra@192.168.200.33
        scp {{.app_bin}} astra@192.168.200.33:~/
        scp config.override.yaml astra@192.168.200.33:~/
        # sudo {{.app_bin}} -config config.override.yaml

  dns:
    cmds:
      - |
        {{.gobin}} build -ldflags="{{.ldflags}}" -trimpath -gcflags="{{.gcflags}}" -asmflags="{{.asmflags}}" \
          -o {{.bin}}/dns dns.go
        strip {{.bin}}/dns
        objcopy --strip-unneeded {{.bin}}/dns
        scp {{.bin}}/dns astra@192.168.200.33:~/
